server:
  port: 8081
  servlet:
    context-path: /v1/credit-loan/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    jdbc-type-for-null: 'Null'
  mapper-locations: /com/ing/hub/credit/loan/repository/*.xml


spring:
  profiles:
    active: local
  application:
    name: loan-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: changeme
    #url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    #username: ${DB_USERNAME:postgres}
    #password: ${DB_PASSWORD:changeme}
    tomcat:
      max-active: 5
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-version: 1
    locations: classpath:/db/migration
    table: schema_history
    schemas: credit
    out-of-order: true
    validate-on-migrate: true
    baseline-on-migrate: false
logging:
  level:
    com:
      ing:
        hub:
          credit:
            loan: DEBUG
  jackson:
    default-property-inclusion: NON_NULL
springdoc:
  api-docs:
    path: /api-docs
  .swagger-ui:
    path: /swagger-ui-custom.html
